// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package provider

// Resource and data-source type-name suffixes. Each constant is appended
// to req.ProviderTypeName in the resource's Metadata method, so the full
// Terraform resource type is e.g. `pve_node`.
//
// Centralizing these strings prevents drift between the implementation
// files (where they are set on resp.TypeName) and the test files (where
// they are asserted against). Tests should reference these constants
// rather than duplicating the literal strings.
const (
	TypeNamePveNode                   = "node"
	TypeNamePveNodeNetworkLinuxBridge = "node_network_linux_bridge"
	TypeNamePveNodeNetworkLinuxBond   = "node_network_linux_bond"
	TypeNamePveNodeNetworkVlan        = "node_network_vlan"
	TypeNamePveNodeDiskZFS            = "node_disk_zfs"
	TypeNamePveNodeDiskLVM            = "node_disk_lvm"
	TypeNamePveNodes                  = "nodes"
	TypeNamePveNodeStatus             = "node_status"
	TypeNamePveNodeDisks              = "node_disks"
	TypeNamePveNodeNetworkInterfaces  = "node_network_interfaces"
	// Phase 1 — access control, cluster core, HA.
	TypeNamePveUser             = "user"
	TypeNamePveUserToken        = "user_token"
	TypeNamePveGroup            = "group"
	TypeNamePveRole             = "role"
	TypeNamePveAcl              = "acl"
	TypeNamePvePermissions      = "permissions"
	TypeNamePveRealmLdap        = "realm_ldap"
	TypeNamePveRealmAd          = "realm_ad"
	TypeNamePveRealmOpenid      = "realm_openid"
	TypeNamePveRealms           = "realms"
	TypeNamePveRealmSync        = "realm_sync"
	TypeNamePveRealmSyncJob     = "realm_sync_job"
	TypeNamePveClusterResources = "cluster_resources"
	TypeNamePveClusterStatus    = "cluster_status"
	TypeNamePveTasks            = "tasks"
	TypeNamePveNextId           = "next_id"
	TypeNamePveClusterNode      = "cluster_node"
	TypeNamePveClusterOptions   = "cluster_options"
	TypeNamePveHaStatus         = "ha_status"
	TypeNamePveHaArm            = "ha_arm"
	TypeNamePveHaGroup          = "ha_group"
	TypeNamePveHaResource       = "ha_resource"
	TypeNamePveHaRule           = "ha_rule"
	TypeNamePveVersion          = "version"
	// Phase 2 — firewall.
	TypeNamePveClusterFirewallOptions     = "cluster_firewall_options"
	TypeNamePveFirewallAlias              = "firewall_alias"
	TypeNamePveFirewallIpset              = "firewall_ipset"
	TypeNamePveFirewallSecurityGroup      = "firewall_security_group"
	TypeNamePveClusterFirewallRules       = "cluster_firewall_rules"
	TypeNamePveNodeFirewallRules          = "node_firewall_rules"
	TypeNamePveGuestFirewallRules         = "guest_firewall_rules"
	TypeNamePveSecurityGroupFirewallRules = "security_group_firewall_rules"
	TypeNamePveVnetFirewallRules          = "vnet_firewall_rules"
	TypeNamePveNodeFirewallOptions        = "node_firewall_options"
	TypeNamePveGuestFirewallOptions       = "guest_firewall_options"
	TypeNamePveSdnFirewallOptions         = "sdn_firewall_options"
	// Phase 3 — backup, replication, metrics, notifications, pools.
	TypeNamePveBackupJob                    = "backup_job"
	TypeNamePveBackupJobs                   = "backup_jobs"
	TypeNamePveReplication                  = "replication"
	TypeNamePveNodeReplications             = "node_replications"
	TypeNamePveMetricsServer                = "metrics_server"
	TypeNamePveNotificationEndpointSendmail = "notification_endpoint_sendmail"
	TypeNamePveNotificationEndpointGoty     = "notification_endpoint_goty"
	TypeNamePveNotificationEndpointSmtp     = "notification_endpoint_smtp"
	TypeNamePveNotificationEndpointWebhook  = "notification_endpoint_webhook"
	TypeNamePveNotificationMatcher          = "notification_matcher"
	TypeNamePveNotificationTargets          = "notification_targets"
	TypeNamePveNotificationTest             = "notification_test"
	TypeNamePvePool                         = "pool"
	// Phase 4 — storage.
	TypeNamePveStorageNfs          = "storage_nfs"
	TypeNamePveStorageCifs         = "storage_cifs"
	TypeNamePveStorageIscsi        = "storage_iscsi"
	TypeNamePveStorageIscsidirect  = "storage_iscsidirect"
	TypeNamePveStorageLvm          = "storage_lvm"
	TypeNamePveStorageLvmthin      = "storage_lvmthin"
	TypeNamePveStorageZfspool      = "storage_zfspool"
	TypeNamePveStorageDirectory    = "storage_directory"
	TypeNamePveStoragePbs          = "storage_pbs"
	TypeNamePveStorageCephfs       = "storage_cephfs"
	TypeNamePveStorageRbd          = "storage_rbd"
	TypeNamePveNodeStorages        = "node_storages"
	TypeNamePveStorageFiles        = "storage_files"
	TypeNamePveFile                = "file"
	TypeNamePveDownloadFile        = "download_file"
	TypeNamePveStoragePruneBackups = "storage_prune_backups"
	// Phase 5 — node ops, disks, ceph, acme, mappings.
	TypeNamePveNodeHosts             = "node_hosts"
	TypeNamePveNodeReboot            = "node_reboot"
	TypeNamePveNodeShutdown          = "node_shutdown"
	TypeNamePveNodeSubscription      = "node_subscription"
	TypeNamePveNodeServices          = "node_services"
	TypeNamePveNodeService           = "node_service"
	TypeNamePveNodeAptRepositories   = "node_apt_repositories"
	TypeNamePveNodeAptUpdate         = "node_apt_update"
	TypeNamePveAptStandardRepository = "apt_standard_repository"
	TypeNamePveNodeTasks             = "node_tasks"
	TypeNamePveNodePciDevices        = "node_pci_devices"
	TypeNamePveNodeUsbDevices        = "node_usb_devices"
	TypeNamePveNodeCapabilities      = "node_capabilities"
	TypeNamePveNodeWakeonlan         = "node_wakeonlan"
	TypeNamePveNodeDiskLvmthin       = "node_disk_lvmthin"
	TypeNamePveNodeDiskDirectory     = "node_disk_directory"
	TypeNamePveCephStatus            = "ceph_status"
	TypeNamePveCephPool              = "ceph_pool"
	TypeNamePveCephOsd               = "ceph_osd"
	TypeNamePveCephMon               = "ceph_mon"
	TypeNamePveAcmeAccount           = "acme_account"
	TypeNamePveAcmePlugins           = "acme_plugins"
	TypeNamePveAcmeDnsPlugin         = "acme_dns_plugin"
	TypeNamePveHardwareMappingPci    = "hardware_mapping_pci"
	TypeNamePveHardwareMappingUsb    = "hardware_mapping_usb"
	TypeNamePveMappingDir            = "mapping_dir"
	TypeNamePveCustomCpuModel        = "custom_cpu_model"
	TypeNamePveNodeCertificate       = "node_certificate"
	TypeNamePveAcmeCertificate       = "acme_certificate"
	// Phase 6 — qemu and lxc guests.
	TypeNamePveVms                       = "vms"
	TypeNamePveVm                        = "vm"
	TypeNamePveVmReboot                  = "vm_reboot"
	TypeNamePveVmSuspend                 = "vm_suspend"
	TypeNamePveVmResume                  = "vm_resume"
	TypeNamePveVmReset                   = "vm_reset"
	TypeNamePveVmMigrate                 = "vm_migrate"
	TypeNamePveVmSnapshot                = "vm_snapshot"
	TypeNamePveVmSnapshotRollback        = "vm_snapshot_rollback"
	TypeNamePveContainers                = "containers"
	TypeNamePveContainer                 = "container"
	TypeNamePveContainerReboot           = "container_reboot"
	TypeNamePveContainerSuspend          = "container_suspend"
	TypeNamePveContainerResume           = "container_resume"
	TypeNamePveContainerMigrate          = "container_migrate"
	TypeNamePveContainerSnapshot         = "container_snapshot"
	TypeNamePveContainerSnapshotRollback = "container_snapshot_rollback"
	// Phase 7 — sdn and p3 sweep.
	TypeNamePveSdnZoneSimple          = "sdn_zone_simple"
	TypeNamePveSdnZoneVlan            = "sdn_zone_vlan"
	TypeNamePveSdnZoneQinq            = "sdn_zone_qinq"
	TypeNamePveSdnZoneVxlan           = "sdn_zone_vxlan"
	TypeNamePveSdnZoneEvpn            = "sdn_zone_evpn"
	TypeNamePveSdnVnet                = "sdn_vnet"
	TypeNamePveSdnSubnet              = "sdn_subnet"
	TypeNamePveSdnController          = "sdn_controller"
	TypeNamePveSdnDns                 = "sdn_dns"
	TypeNamePveSdnIpam                = "sdn_ipam"
	TypeNamePveSdnPrefixList          = "sdn_prefix_list"
	TypeNamePveSdnRouteMap            = "sdn_route_map"
	TypeNamePveSdnApply               = "sdn_apply"
	TypeNamePveSdnRollback            = "sdn_rollback"
	TypeNamePveSdnFabricOspf          = "sdn_fabric_ospf"
	TypeNamePveSdnFabricOpenfabric    = "sdn_fabric_openfabric"
	TypeNamePveUserTfaUnlock          = "user_tfa_unlock"
	TypeNamePveHaResourceMigrate      = "ha_resource_migrate"
	TypeNamePveHaResourceRelocate     = "ha_resource_relocate"
	TypeNamePveReplicationScheduleNow = "replication_schedule_now"
	TypeNamePveBackupRun              = "backup_run"
	TypeNamePveSubscriptionRefresh    = "subscription_refresh"
	TypeNamePveNodeDiskInitgpt        = "node_disk_initgpt"
	TypeNamePveTaskCancel             = "task_cancel"
	TypeNamePveAppliances             = "appliances"
	TypeNamePveAplinfoUpdate          = "aplinfo_update"
	TypeNamePveStorageOciPull         = "storage_oci_pull"
	TypeNamePveVmAgentInfo            = "vm_agent_info"
	TypeNamePveNodeExecute            = "node_execute"
	TypeNamePveNodeStartAll           = "node_start_all"
	TypeNamePveNodeStopAll            = "node_stop_all"
	TypeNamePveNodeSuspendAll         = "node_suspend_all"
	TypeNamePveNodeMigrateAll         = "node_migrate_all"
	TypeNamePveGuestBulkStart         = "guest_bulk_start"
	TypeNamePveGuestBulkShutdown      = "guest_bulk_shutdown"
	TypeNamePveGuestBulkSuspend       = "guest_bulk_suspend"
	TypeNamePveGuestBulkMigrate       = "guest_bulk_migrate"
)
